name: HTML documentation build
on:
  workflow_call:
jobs:
  build-html:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NNCF and doc requirements
        run: |
          pip install -e .
          pip install -r docs/api/requirements.txt
      - name: Build API docs
        run: |
          sphinx-build -M html "docs/api/source" "html_build"
      - name: Upload built HTMLs as job artifact
        uses: actions/upload-artifact@v3
        with:
          name: html_doc_artifact
          path: html_build
