name: Config schema HTML build
on:
  pull_request_target:
    branches:
      - develop
    paths:
      - nncf/config/**

jobs:
  build-config-schema-html:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          pip install json-schema-for-humans
          pip install -e .
          python -c 'import jstyleson; from nncf.config import NNCFConfig; jstyleson.dump(NNCFConfig.schema(), open("./schema.json", "w"), indent=2)'
          mkdir schema_html_build
          generate-schema-doc --deprecated-from-description schema.json schema/index.html